#!/bin/bash
#SBATCH --job-name=metabolicDWH      # Job name
#SBATCH --partition=batch         # Partition (queue) name
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --mem=100gb                     # Job memory request
#SBATCH --time=20:00:00               # Time limit hrs:min:sec
#SBATCH --output=testserial.%j.out    # Standard output log
#SBATCH --error=testserial.%j.err     # Standard error log

#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=rck80079@uga.edu  # Where to send mail

cd /scratch/rck80079/

module load METABOLIC/3.0-foss-2019b
Perl/5.30.0-GCCcore-8.3.0

perl /scratch/rck80079/METABOLIC-G.pl -in-gn /scratch/rck80079/DWH_fasta -o /scratch/rck80079/METABOLIC_DWH
